# Generated by Django 3.2.6 on 2024-02-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
