# Generated by Django 3.2.6 on 2024-02-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_products_in_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecommerce.basemodel')),
                ('charge_id', models.CharField(max_length=255)),
            ],
            bases=('ecommerce.basemodel',),
        ),
    ]
