# Generated by Django 3.2.6 on 2024-02-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='charge_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
